import { api } from '../api.js';
import { esc, toast, openModal, closeModal, loadingHTML, emptyHTML, noop, safeCb, paginationHTML, paginateRows, bindPagination } from '../utils.js';

const FALLBACK_TYPES = [
  { code:'annual', name:'Phép năm', paid_policy:'paid', deducts_annual_leave:1, short_description:'Dùng số ngày phép năm còn lại của bạn', policy_description:'Áp dụng cho nhu cầu nghỉ cá nhân và trừ vào số dư phép năm.' },
  { code:'compensatory', name:'Nghỉ bù', paid_policy:'paid', short_description:'Dùng ngày hoặc giờ nghỉ bù đã tích lũy', policy_description:'Chỉ đăng ký trong phạm vi số dư nghỉ bù hiện có.' },
  { code:'sick', name:'Nghỉ ốm', paid_policy:'paid', requires_evidence:1, short_description:'Nghỉ do ốm đau hoặc điều trị', policy_description:'Có thể yêu cầu giấy khám bệnh hoặc giấy xác nhận y tế.' },
  { code:'personal_paid', name:'Nghỉ việc riêng hưởng lương', paid_policy:'paid', short_description:'Việc cá nhân thuộc trường hợp được hưởng lương', policy_description:'Cần nêu rõ lý do để quản lý xem xét.' },
  { code:'personal', name:'Nghỉ việc riêng không hưởng lương', paid_policy:'unpaid', short_description:'Nghỉ cá nhân không thuộc trường hợp hưởng lương', policy_description:'Thời gian nghỉ không được tính lương.' },
  { code:'unpaid', name:'Nghỉ không hưởng lương', paid_policy:'unpaid', short_description:'Nghỉ cá nhân và không tính lương', policy_description:'Cần cấp có thẩm quyền phê duyệt.' },
  { code:'maternity', name:'Nghỉ thai sản', paid_policy:'paid', requires_evidence:1, requires_bod_approval:1, short_description:'Nghỉ theo chế độ thai sản', policy_description:'Cần thời gian dự kiến nghỉ và tài liệu theo chính sách công ty.' },
  { code:'other', name:'Khác', paid_policy:'configurable', short_description:'Chỉ chọn khi không có loại nghỉ phù hợp', policy_description:'Bắt buộc nhập lý do chi tiết để HCNS kiểm tra và phân loại.' },
];

const paidLabel = type => type.paid_policy === 'unpaid' ? 'Không hưởng lương' : type.paid_policy === 'configurable' ? 'Theo chế độ' : 'Có hưởng lương';
const paidClass = type => type.paid_policy === 'unpaid' ? 'badge-danger' : type.paid_policy === 'configurable' ? 'badge-warning' : 'badge-success';
const sessionLabel = value => ({ full:'Cả ngày', morning:'Buổi sáng', afternoon:'Buổi chiều' })[value] || 'Cả ngày';
const statusData = status => ({ pending:['badge-warning','⏳ Chờ duyệt'], approved:['badge-success','✅ Đã duyệt'], rejected:['badge-danger','❌ Từ chối'] }[status] || ['badge-gray', status]);
const daysBetween = (start, end, session = 'full') => {
  if (!start || !end || start > end) return 0;
  let days = 0, cursor = new Date(`${start}T00:00:00`), finish = new Date(`${end}T00:00:00`);
  while (cursor <= finish) { if (cursor.getDay() !== 0 && cursor.getDay() !== 6) days += 1; cursor.setDate(cursor.getDate() + 1); }
  return session === 'full' ? days : (start === end ? 0.5 : 0);
};

export async function renderLeave(el, me) {
  const canConfigure = me.role === 'admin' || me.department === 'Phòng HCNS';
  const canReview = canConfigure || me.role === 'manager' || me.department === 'Ban Giám Đốc';
  let types = FALLBACK_TYPES, currentPage = 1;
  try { const data = await api.getLeaveTypes(false); if (data.leaveTypes?.length) types = data.leaveTypes; } catch (_) {}
  el.innerHTML = `<div class="page-header"><div class="page-header-left"><div class="page-title">🏖️ Nghỉ phép</div><div class="page-sub">Xin nghỉ, kiểm tra chính sách và theo dõi phê duyệt</div></div><div style="display:flex;gap:8px;flex-wrap:wrap;">${canConfigure ? '<button id="leave-balance" class="btn-secondary btn-sm">⚖️ Điều chỉnh số dư</button><button id="leave-policy" class="btn-secondary btn-sm">⚙️ Cấu hình loại nghỉ</button>' : ''}<button id="btn-new-leave" class="btn-primary btn-sm">+ Xin nghỉ</button></div></div><div class="filter-bar" id="leave-filters"><span class="filter-chip active" data-status="">Tất cả</span><span class="filter-chip" data-status="pending">⏳ Chờ duyệt</span><span class="filter-chip" data-status="approved">✅ Đã duyệt</span><span class="filter-chip" data-status="rejected">❌ Từ chối</span></div>${canReview ? '<input id="leave-search" placeholder="Tìm theo tên, mã nhân viên..." style="width:100%;max-width:420px;margin-bottom:12px;"/>' : ''}<div id="leave-list">${loadingHTML()}</div>`;
  el.querySelector('#btn-new-leave').addEventListener('click', () => openLeaveForm(me, types, loadLeave));
  el.querySelector('#leave-policy')?.addEventListener('click', () => openPolicyConfig(types, async () => { const data = await api.getLeaveTypes(false); types = data.leaveTypes; }));
  el.querySelector('#leave-balance')?.addEventListener('click', () => openBalanceAdjustment());
  el.querySelector('#leave-filters').addEventListener('click', event => { const chip = event.target.closest('.filter-chip'); if (!chip) return; el.querySelectorAll('#leave-filters .filter-chip').forEach(x => x.classList.toggle('active', x === chip)); currentPage = 1; loadLeave(); });
  el.querySelector('#leave-search')?.addEventListener('input', () => { currentPage = 1; loadLeave(); });

  async function loadLeave() {
    const list = el.querySelector('#leave-list'); list.innerHTML = loadingHTML();
    try {
      const status = el.querySelector('#leave-filters .active')?.dataset.status || '';
      const { leave = [] } = await api.getLeave(status ? { status } : {});
      const search = (el.querySelector('#leave-search')?.value || '').toLocaleLowerCase('vi');
      const filtered = leave.filter(row => !search || `${row.employee_name || ''} ${row.employee_code || ''}`.toLocaleLowerCase('vi').includes(search));
      const page = paginateRows(filtered, currentPage); currentPage = page.page;
      if (!filtered.length) { list.innerHTML = emptyHTML('🏖️', 'Không có đơn nghỉ phép nào', 'Nhấn “+ Xin nghỉ” để tạo đơn mới'); return; }
      list.innerHTML = page.rows.map(row => { const [cls,label] = statusData(row.status); const type = types.find(x => x.code === row.type) || row; return `<div class="leave-item"><div class="leave-type-icon" style="background:var(--primary-light);">🏖️</div><div style="flex:1;min-width:0;"><div style="display:flex;gap:7px;align-items:center;flex-wrap:wrap;"><strong>${esc(row.type_name || type.name || row.type)}</strong><span class="badge ${paidClass(row)}">${esc(row.paid_label || paidLabel(row))}</span><span class="badge ${cls}">${label}</span></div>${canReview && row.employee_name ? `<div style="font-size:12px;color:var(--text-2);margin-top:3px;">👤 ${esc(row.employee_name)} · ${esc(row.department || '')}</div>` : ''}<div style="font-size:12px;color:var(--text-2);margin-top:4px;">📅 ${esc(row.start_date)} → ${esc(row.end_date)} · ${sessionLabel(row.leave_session)} · <strong>${row.total_days ?? daysBetween(row.start_date,row.end_date,row.leave_session)} ngày</strong></div><div style="font-size:12px;color:var(--text-3);margin-top:4px;">${esc(row.reason || '')}${row.handover_user_name ? ` · Bàn giao: ${esc(row.handover_user_name)}` : ''}${row.document_count ? ` · 📎 ${row.document_count} tệp` : ''}</div>${row.current_approver ? `<div style="font-size:12px;color:var(--primary);margin-top:3px;">Đang chờ: ${esc(row.current_approver)}</div>` : ''}</div><div style="display:flex;gap:6px;align-items:center;">${row.can_action ? '<button class="btn-xs btn-primary leave-approve" data-id="'+row.id+'">Duyệt</button><button class="btn-xs btn-danger leave-reject" data-id="'+row.id+'">Từ chối</button>' : ''}${Number(row.employee_id) === Number(me.id) && row.status === 'pending' ? '<button class="btn-xs btn-secondary leave-delete" data-id="'+row.id+'">Xóa</button>' : ''}</div></div>`; }).join('') + paginationHTML(page);
      list.querySelectorAll('.leave-approve').forEach(button => button.addEventListener('click', async () => { try { await api.updateLeave(button.dataset.id, { status:'approved' }); toast('Đã chuyển đơn sang bước tiếp theo', 'success'); loadLeave(); } catch (error) { toast(error.message, 'error'); } }));
      list.querySelectorAll('.leave-reject').forEach(button => button.addEventListener('click', async () => { const note = prompt('Ghi chú từ chối (không bắt buộc):') || ''; try { await api.updateLeave(button.dataset.id, { status:'rejected', note }); toast('Đã từ chối đơn', 'info'); loadLeave(); } catch (error) { toast(error.message, 'error'); } }));
      list.querySelectorAll('.leave-delete').forEach(button => button.addEventListener('click', async () => { if (!confirm('Xóa đơn nghỉ này? Số dư đã giữ chỗ sẽ được hoàn lại.')) return; try { await api.deleteLeave(button.dataset.id); toast('Đã xóa đơn nghỉ', 'success'); loadLeave(); } catch (error) { toast(error.message, 'error'); } }));
      bindPagination(list, next => { currentPage = next; loadLeave(); });
    } catch (error) { list.innerHTML = emptyHTML('⚠️', error.message); }
  }
  loadLeave();
}

async function openLeaveForm(me, types, refresh = noop) {
  refresh = safeCb(refresh); const today = new Date().toISOString().slice(0,10);
  const { balances = [] } = await api.getLeaveBalances({ year: new Date().getFullYear() }).catch(() => ({ balances: [] }));
  const { users = [] } = await api.getUsersBasic().catch(() => ({ users: [] }));
  const balanceOf = code => Number(balances.find(x => x.leave_type_code === code)?.available_days || 0);
  const render = selectedCode => {
    const type = types.find(x => x.code === selectedCode); const maternity = selectedCode === 'maternity';
    const balanceCode = type?.deducts_annual_leave ? 'annual' : selectedCode === 'compensatory' ? 'compensatory' : null;
    const docText = type?.required_documents || (type?.requires_evidence ? 'Tài liệu minh chứng bắt buộc' : 'Không yêu cầu tài liệu đính kèm');
    return `<div class="field"><label>Loại nghỉ phép *</label><select id="lf-type"><option value="">Chọn loại nghỉ phép phù hợp</option>${types.map(x => `<option value="${esc(x.code)}" ${x.code===selectedCode?'selected':''}>${esc(x.name)} — ${paidLabel(x)}</option>`).join('')}</select></div>${type ? `<div class="card" style="padding:14px;margin:0 0 12px;border-color:var(--primary);"><div style="display:flex;gap:7px;align-items:center;"><strong>${esc(type.name)}</strong><span class="badge ${paidClass(type)}">${paidLabel(type)}</span></div><div style="font-size:13px;color:var(--text-2);margin-top:7px;">${esc(type.policy_description || type.short_description || 'Theo chính sách công ty.')}</div>${balanceCode ? `<div style="font-size:13px;margin-top:7px;">Số dư hiện tại: <strong>${balanceOf(balanceCode)} ngày</strong></div>` : ''}<div style="font-size:12px;color:var(--text-2);margin-top:5px;">Hồ sơ: ${esc(docText)} · Duyệt: ${type.approval_flow === 'manager_hr_bgd' || type.requires_bod_approval ? 'Quản lý → HCNS → Ban giám đốc' : 'Quản lý → HCNS'}${type.notice_hours != null ? ` · Gửi trước ${type.notice_hours} giờ` : ''}</div></div>` : ''}<div class="input-row"><div class="field"><label>${maternity ? 'Ngày dự kiến bắt đầu nghỉ' : 'Từ ngày'} *</label><input type="date" id="lf-start" value="${today}"/></div><div class="field"><label>${maternity ? 'Ngày dự kiến kết thúc nghỉ' : 'Đến ngày'} *</label><input type="date" id="lf-end" value="${today}"/></div></div>${maternity ? '' : '<div class="field"><label>Ca nghỉ *</label><select id="lf-session"><option value="full">Cả ngày</option><option value="morning">Buổi sáng</option><option value="afternoon">Buổi chiều</option></select></div>'}<div class="field"><label>Lý do nghỉ *</label><textarea id="lf-reason" rows="3" placeholder="Nhập lý do cụ thể..."></textarea></div><div class="field"><label>Tài liệu đính kèm ${type?.requires_evidence ? '*' : ''}</label><input type="file" id="lf-files" accept=".pdf,image/jpeg,image/png,image/webp" multiple/><div class="field-hint">PDF, JPG, PNG hoặc WebP; tối đa 10 MB mỗi tệp.</div></div><div class="field"><label>Người bàn giao công việc</label><select id="lf-handover"><option value="">Chọn người bàn giao (bắt buộc nếu nghỉ từ 2 ngày)</option>${users.filter(user => Number(user.id)!==Number(me.id)).map(user => `<option value="${user.id}">${esc(user.full_name)}${user.employee_code ? ` — ${esc(user.employee_code)}` : ''}</option>`).join('')}</select></div><div id="lf-total" style="text-align:center;padding:10px;background:var(--primary-light);border-radius:8px;font-size:13px;font-weight:600;color:var(--primary);"></div>`;
  };
  openModal('Đăng ký nghỉ phép', `<div id="leave-form-body">${render('')}</div>`, '<button class="btn-secondary" onclick="document.getElementById(\'modal-overlay\').classList.add(\'hidden\')">Hủy</button><button class="btn-primary" id="lf-save">Gửi đơn</button>');
  const body = document.getElementById('leave-form-body');
  const bind = () => {
    const typeSelect = document.getElementById('lf-type'); typeSelect.addEventListener('change', () => { body.innerHTML = render(typeSelect.value); bind(); });
    const updateTotal = () => { const days = daysBetween(document.getElementById('lf-start').value, document.getElementById('lf-end').value, document.getElementById('lf-session')?.value || 'full'); document.getElementById('lf-total').textContent = days ? `Tổng cộng: ${days} ngày nghỉ` : 'Chọn khoảng thời gian hợp lệ'; };
    document.getElementById('lf-start').addEventListener('change', updateTotal); document.getElementById('lf-end').addEventListener('change', updateTotal); document.getElementById('lf-session')?.addEventListener('change', updateTotal); updateTotal();
  }; bind();
  document.getElementById('lf-save').addEventListener('click', async () => { const type = document.getElementById('lf-type').value, start = document.getElementById('lf-start').value, end = document.getElementById('lf-end').value, session = document.getElementById('lf-session')?.value || 'full', reason = document.getElementById('lf-reason').value.trim(); const policy = types.find(x => x.code === type); if (!type || !start || !end || !reason) { toast('Vui lòng chọn loại nghỉ, ngày nghỉ và nhập lý do', 'error'); return; } if (start > end || (session !== 'full' && start !== end)) { toast('Khoảng thời gian hoặc ca nghỉ không hợp lệ', 'error'); return; } const button = document.getElementById('lf-save'); button.disabled = true; try { const files = [...document.getElementById('lf-files').files]; if (policy?.requires_evidence && !files.length) throw new Error('Loại nghỉ này yêu cầu tài liệu đính kèm'); const documentIds = []; for (const file of files) { const uploaded = await api.uploadLeaveDocument(file); documentIds.push(uploaded.id); } await api.createLeave({ type, start_date:start, end_date:end, leave_session:session, reason, handover_user_id:document.getElementById('lf-handover').value || null, document_ids:documentIds }); closeModal(); toast('Đã gửi đơn nghỉ phép', 'success'); refresh(); } catch (error) { toast(error.message, 'error'); button.disabled = false; } });
}

function openPolicyConfig(types, onSaved) {
  const show = type => { openModal('Cấu hình loại nghỉ', `<div class="field"><label>Loại nghỉ</label><select id="lp-choice">${types.map(x => `<option value="${x.id}" ${x.id===type.id?'selected':''}>${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label>Mô tả ngắn</label><input id="lp-short" value="${esc(type.short_description || '')}"/></div><div class="field"><label>Diễn giải chính sách</label><textarea id="lp-detail" rows="3">${esc(type.policy_description || '')}</textarea></div><div class="input-row"><div class="field"><label>Hạn gửi trước (giờ)</label><input id="lp-notice" type="number" min="0" value="${type.notice_hours ?? ''}" placeholder="Theo chính sách"/></div><div class="field"><label>Luồng duyệt</label><select id="lp-flow"><option value="manager_hr" ${type.approval_flow==='manager_hr'?'selected':''}>Quản lý → HCNS</option><option value="manager_hr_bgd" ${type.approval_flow==='manager_hr_bgd'?'selected':''}>Quản lý → HCNS → BGD</option></select></div></div><div class="field"><label>Tài liệu yêu cầu</label><input id="lp-docs" value="${esc(type.required_documents || '')}" placeholder="Ví dụ: Giấy khám bệnh"/></div><label style="display:block;margin:10px 0;"><input id="lp-evidence" type="checkbox" ${type.requires_evidence?'checked':''}/> Bắt buộc đính kèm tài liệu</label><label style="display:block;margin:10px 0;"><input id="lp-handover" type="checkbox" ${type.requires_handover?'checked':''}/> Luôn yêu cầu bàn giao công việc</label>`, '<button class="btn-secondary" onclick="document.getElementById(\'modal-overlay\').classList.add(\'hidden\')">Hủy</button><button class="btn-primary" id="lp-save">Lưu cấu hình</button>'); document.getElementById('lp-choice').addEventListener('change', event => show(types.find(x => String(x.id)===event.target.value))); document.getElementById('lp-save').addEventListener('click', async () => { try { await api.updateLeaveType(type.id, { ...type, short_description:document.getElementById('lp-short').value, policy_description:document.getElementById('lp-detail').value, notice_hours:document.getElementById('lp-notice').value, required_documents:document.getElementById('lp-docs').value, requires_evidence:document.getElementById('lp-evidence').checked, requires_handover:document.getElementById('lp-handover').checked, approval_flow:document.getElementById('lp-flow').value }); await onSaved(); closeModal(); toast('Đã lưu cấu hình loại nghỉ', 'success'); } catch (error) { toast(error.message, 'error'); } }); }; show(types[0]);
}

async function openBalanceAdjustment() {
  const { users = [] } = await api.getUsersBasic(); openModal('Điều chỉnh số dư nghỉ', `<div class="field"><label>Nhân viên *</label><select id="lb-user"><option value="">Chọn nhân viên</option>${users.filter(user => user.is_active).map(user => `<option value="${user.id}">${esc(user.full_name)}${user.employee_code ? ` — ${esc(user.employee_code)}` : ''}</option>`).join('')}</select></div><div class="input-row"><div class="field"><label>Loại số dư</label><select id="lb-type"><option value="annual">Phép năm</option><option value="compensatory">Nghỉ bù</option></select></div><div class="field"><label>Điều chỉnh (ngày)</label><input id="lb-delta" type="number" step="0.5" placeholder="Ví dụ: 1 hoặc -0.5"/></div></div><div class="field"><label>Ghi chú *</label><textarea id="lb-note" rows="2" placeholder="Lý do điều chỉnh số dư..."></textarea></div>`, '<button class="btn-secondary" onclick="document.getElementById(\'modal-overlay\').classList.add(\'hidden\')">Hủy</button><button class="btn-primary" id="lb-save">Lưu điều chỉnh</button>'); document.getElementById('lb-save').addEventListener('click', async () => { try { await api.adjustLeaveBalance({ user_id:Number(document.getElementById('lb-user').value), leave_type_code:document.getElementById('lb-type').value, delta_days:Number(document.getElementById('lb-delta').value), note:document.getElementById('lb-note').value.trim() }); closeModal(); toast('Đã điều chỉnh số dư', 'success'); } catch (error) { toast(error.message, 'error'); } });
}
